### ISSUE TITLE
Feature and question

### ISSUE THREAD

**Issue by GardoTL** [sunls24/temporary-mail#3]
Hi, could you please make a language selector with English because your website is great but it's very complicated to understand the buttons.

Question:
Is it possible to use my custom domain names if I want to self-host?

**Comment by sunls24** [comment]
Thank you very much for your recognition. Currently, there are no plans to add multiple languages because the function itself is quite simple. Perhaps you can use Google Translate.

This is the latest deployment document [Self-built Deployment Tutorial](https://github.com/sunls24/temporary-mail/blob/main/deploy.md). Unfortunately, this is also in Chinese.
